from collections import deque

d = deque()
d.append(1)
d.append(2)
print(d)
d.appendleft(3)
print(d)
d.pop()
print(d)
d.popleft()
print(d)
d.extend([4, 5, 6])
print(d)
d.extendleft([8, 9])
print(d)
d.rotate(1)
print(d)
d.clear()
print(d)


#result: deque([1, 2])
#result: deque([3, 1, 2])
#result: deque([3, 1])
#result: deque([1])
#result: deque([1, 4, 5, 6])
#result: deque([9, 8, 1, 4, 5, 6])
#result: deque([6, 9, 8, 1, 4, 5])
#result: deque([])